from djitellopy import TelloSwarm
import time

# After all swarm drones are turned on and their propellers are spinning, go to the router and find
# the ip addresses of every device with hostname that starts with RMTT-.
# Add the ip address to this list. Do this only when you are going to run the code with the drones.
swarm = TelloSwarm.fromIps([
    "192.168.1.182",
    "192.168.1.147",
    "192.168.1.131"
])

mapping_id_to_ssid = {}
# Use the commands dictionary object to store the command for each drone according to
# to the SSID of the TT module. For every drone you need these:
# commands['ssid of tt module'] = [] : purpose to declare an empty array for that drone
# commands['ssid of tt module'].append('command') : add command for that drone one by one.
# google Robomaster TT sdk for a pdf that contains the command that can used to command  the drone.
commands= {}
commands['RMTT-330AD6'] = []
commands['RMTT-330AD6'].append("takeoff")
commands['RMTT-330AD6'].append("go 100 100 50 60")
commands['RMTT-330AD6'].append("land")
commands['RMTT-3B3B0A'] = []
commands['RMTT-3B3B0A'].append("takeoff")
commands['RMTT-3B3B0A'].append("go -100 -100 50 60")
commands['RMTT-3B3B0A'].append("land")
commands['RMTT-33042A'] = []
commands['RMTT-33042A'].append("takeoff")
commands['RMTT-33042A'].append("cw 90")
commands['RMTT-33042A'].append("land")

# this is used by djitellopy.swarm.parallel to issue commands to each drone in the swarms.
# second most important function as this issues the command in the array to each drone in parellel.
# If you wish to wanting to make specific drones to drone computer vision stuff, you could do by 
# modifying the runcmd. You need to add an if-else statement to check if the ssid is that drone you are wanting
# to do computer vision with, and then add specific codes (such as streamon) for that drone within that if statement.
# Please keep it to one drone for the time being unless you know how to modify djitellopy to receive video at 
# ports that is different from what djitellopy is using.
def runcmd(i,tello):
    global commands
    global mapping_id_to_ssid
    ssid = mapping_id_to_ssid[i]
    cmds = commands[ssid]
    for cmd in cmds:
        print(cmd)
        resp = tello.send_command_with_return(cmd)
        time.sleep(5)
        print(resp)

# most important function as this ask the drone its ssid and map it
# to id generated by djitellopy
def getWIFI(i,tello):
    global mapping_id_to_ssid
    ssid = tello.send_command_with_return('ssid?')
    print(ssid)
    mapping_id_to_ssid[i] = ssid

def onMission(i,tello):
    tello.enable_mission_pads()

swarm.connect()
swarm.parallel(getWIFI)
swarm.parallel(onMission)
swarm.parallel(runcmd)
swarm.end()

#commands
tello.send_command_with_return()